NPA
- https://npa.go.ug/institutional-strategic-plans/
- https://npa.go.ug/cndpf/
- 
Quick recap
Ukubona and Vincent conducted a meeting to prepare for an upcoming presentation about a digital twin solution for Uganda. They reviewed the key features of the digital twin platform, including district locations, color-coded heat maps, drop-down menus for indicators, data pipelines, and Uganda's data sovereignty. Ukubona provided guidance on how to present the solution effectively, emphasizing the importance of latency reduction in data decision-making and avoiding technical jargon like AI. They discussed how the platform could be expanded to include various indicators beyond health metrics, such as those from Uganda's National Planning Authority's Vision 2040 and national development plans. The meeting focused on highlighting the digital twin's ability to provide real-time data representation and support priority-setting through customizable indicators, with Ukubona suggesting that the platform's value would increase over time as more data and indicators are integrated.
Next steps
- Ukubona: Update the presentation to change "Chief SICT" to "Manager" as requested by Vincent.
- Vincent: Share the URL or link to the public M&E framework/indicator data with Ukubona for integration into the digital twin's drop-down menu.
- Ukubona: Update the digital twin to include additional indicators and data from the M&E framework shared by Vincent, to make the twin more representative of Uganda's planning data.
- Ukubona: Investigate and address the technical issue with navigation/back functionality in the demo (noted during the meeting when refreshing or using back arrow did not return to the map view).
- Ukubona: Consider adding a navigation bar to the demo for easier movement between sections, as discussed.
- Ukubona: Explore enabling what-if scenario updates to reflect real-time or future data in the digital twin, as suggested by Vincent.
Summary
Digital Twin Board Presentation
Ukubona and Vincent discussed a presentation for the board about a digital twin solution. They reviewed a shared document containing updated district information. Vincent planned to present the solution as a tool for quick decision-making, emphasizing the concept of digital twins rather than focusing on specific technologies like AI. Ukubona advised against overusing the term "AI" in the presentation, suggesting it was more than just AI.
Digital Twin of Uganda Dashboard
Ukubona and Vincent discussed the concept of a digital twin as a representation that needs to stay alive to function properly. Vincent explained a solution that creates a digital twin of Uganda, processing and cleaning data to provide a dashboard with statistics and color-coded indicators showing levels of intensity or need for action. The system is customizable based on different data sets and can display information about locations, districts, infrastructure, and resources.
Indicator Display System Redesign Discussion
Vincent and Ukubona discussed changing from color codes to a drop-down menu system for displaying indicators, with Ukubona explaining that the drop-down menu approach is more scalable as it can accommodate all policy topics and diseases NPA addresses. They reviewed how different indicators show varying levels of spread through color coding, with red representing the highest intensity or "hottest zone" in a heat map visualization. The discussion also covered the different components of the system, including district location, color codes, drop-down menus, and API data pipeline functionality, with Ukubona advising Vincent to focus on basic features and avoid technical details when presenting to district officers.
Digital Map Interface Technical Issues
Ukubona and Vincent discussed navigating a digital map interface, encountering technical issues with page refreshes not returning to the map view as expected. They explored what-if scenarios by adjusting parameters, specifically reducing Kampala's value to 0.4, though they encountered some technical difficulties with the interface not reflecting the changes immediately. Vincent confirmed his understanding of the what-if functionality and asked about connecting APIs to different pipelines, to which Ukubona confirmed this was possible.
Data Sovereignty Presentation Planning
Ukubona and Vincent discussed the presentation flow, focusing on technical language and data sovereignty in Uganda. They clarified the distinction between data protection laws and data sovereignty regulations, confirming that government entities would be in charge of holding the data. Ukubona advised Vincent on navigating the presentation slides, suggesting specific points to highlight, including the heat map and color-coded examples for critical and urgent matters.
Uganda Digital Twin System Demo
Ukubona demonstrated a digital twin system for Uganda that uses color coding to show data stability (blue) and losses (red) across different districts. He explained how the system includes clickable indicators and a data pipeline to address delays in data transfer from districts to NPA. The discussion focused on how Vincent could present the system, suggesting he could share the link and explain the digital twin concept at the beginning, then dive into specific details about districts, colors, and the API functionality. The conversation ended with Vincent asking about the meaning of 33.8% but the answer was not captured in the transcript.
Health Priority Mapping Demonstration
Ukubona explained to Vincent how to use a drop-down menu and sliders to set priorities and weight different health issues in a composite problem map for Uganda. He demonstrated how adjusting the priority of mental health affects the color representation on the map, showing that higher priority for mental health reveals more red areas in the north. Ukubona emphasized that this method quantifies priorities that are often set informally, allowing policymakers to see the impact of their weighting decisions on resource allocation.
Healthcare Budget Priority Setting Tool
Ukubona explained priority setting in healthcare budgeting, demonstrating how to allocate resources when facing constrained budgets. Vincent asked about updating the current status data and generating what-if scenarios in the tool. Ukubona confirmed that while the current demo used static 2025 report data, the tool could indeed generate dynamic reports with transparent formulas that show how priority changes affect savings and risks.
Digital Transformation Program Discussion
Vincent and Ukubona discussed a digital transformation program and its indicators, including increasing national backbone fiber and its dependence on electricity availability. Vincent explained how the system could display real-time data and impact relationships between different indicators. He also shared an example from the National Planning Authority's Vision 2040 and national development plans, highlighting how targets and indicators could be tracked and displayed on a map for accountability.
Uganda Twin System Update Discussion
Vincent and Ukubona discussed updating a twin system to better represent Uganda's goals and aspirations by incorporating data from their M&E framework, which is publicly available on the website. They explored how different ministries and departments could be aligned with the plan through implementation action plans. The conversation focused on using this information to enhance the representation on a map, with Ukubona planning to incorporate it into a presentation's third part, which includes district information and color coding.
Digital Twin System Development
Ukubona and Vincent discussed the development of a digital twin system with drop-down menus for various metrics and indicators, including maternal mortality and quality of life measures. They emphasized the importance of latency in decision-making and how the digital twin can help collapse delays between ground reality and central decisions. The system will initially use existing data and Excel files, with plans to expand the indicators over time. Vincent will be presenting the system to Parliament, and they agreed to continue discussions about translating Excel information into the drop-down menu format.
